apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: nominal-code-config
    namespace: nominal-code
    files:
      - config.yaml
    options:
      disableNameSuffixHash: true
