apiVersion: v1
kind: Service
metadata:
  name: nominal-code-controller
  namespace: nominal-code
  labels:
    app.kubernetes.io/name: nominal-code
    app.kubernetes.io/component: controller
spec:
  selector:
    app.kubernetes.io/name: nominal-code
    app.kubernetes.io/component: controller
  ports:
    - port: 80
      targetPort: 8080
